apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: voting-app-cluster
spec: 
  template:
    metadata: 
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app-cluster
    spec:
      containers: 
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app-cluster
