apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deploy
  labels:
    name: redis-deploy
    app: voting-app-cluster
spec: 
  template:
    metadata: 
      name: redis-pod
      labels:
        name: redis-pod
        app: voting-app-cluster
    spec:
      containers: 
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: voting-app-cluster
