apiVersion: apps/v1
kind: Deployment
metadata: 
  name: result-deploy
  labels:
    name: result-deploy
    app: voting-app-cluster
spec: 
  template:
    metadata: 
      name: result-pod
      labels:
        name: result-pod
        app: voting-app-cluster
    spec:
      containers: 
        - name: result-image
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
      app: voting-app-cluster
