apiVersion: v1 
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-app-cluster
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30006
    targetPort: 80
  selector:
    name: result-service
    app: voting-app-cluster