apiVersion: v1 
kind: Service
metadata: 
  name: voting-service
  labels: 
    name: voting-service
    app: voting-app-cluster
spec: 
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005
    targetPort: 80
  selector:
    name: voting-service
    app: voting-app-cluster