apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deploy
  labels:
    name: worker-deploy
    app: voting-app-cluster
spec: 
  template:
    metadata: 
      name: worker-pod
      labels:
        name: worker-pod
        app: voting-app-cluster
    spec:
      containers: 
      - name: worker-image
        image: kodekloud/examplevotingapp_worker:v1
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: voting-app-cluster
